export const stockData = [
  { ticker: 'AAPL', title: 'Apple Inc.', sector: 'Technology', profitMargin: 0.25, pe: 28, marketCap: 2800 },
  { ticker: 'MSFT', title: 'Microsoft Corp.', sector: 'Technology', profitMargin: 0.30, pe: 32, marketCap: 2500 },
  { ticker: 'GOOGL', title: 'Alphabet Inc.', sector: 'Communication Services', profitMargin: 0.22, pe: 27, marketCap: 1800 },
  { ticker: 'AMZN', title: 'Amazon.com Inc.', sector: 'Consumer Discretionary', profitMargin: 0.10, pe: 60, marketCap: 1700 },
  { ticker: 'TSLA', title: 'Tesla Inc.', sector: 'Consumer Discretionary', profitMargin: 0.12, pe: 80, marketCap: 900 },
  { ticker: 'JNJ', title: 'Johnson & Johnson', sector: 'Healthcare', profitMargin: 0.18, pe: 25, marketCap: 450 },
  { ticker: 'JPM', title: 'JPMorgan Chase & Co.', sector: 'Financials', profitMargin: 0.28, pe: 12, marketCap: 400 },
  { ticker: 'V', title: 'Visa Inc.', sector: 'Financials', profitMargin: 0.55, pe: 35, marketCap: 500 },
  { ticker: 'PG', title: 'Procter & Gamble Co.', sector: 'Consumer Staples', profitMargin: 0.20, pe: 24, marketCap: 350 },
  { ticker: 'NVDA', title: 'NVIDIA Corp.', sector: 'Technology', profitMargin: 0.35, pe: 45, marketCap: 800 },
  { ticker: 'DIS', title: 'The Walt Disney Co.', sector: 'Communication Services', profitMargin: 0.08, pe: 30, marketCap: 300 },
  { ticker: 'NFLX', title: 'Netflix Inc.', sector: 'Communication Services', profitMargin: 0.15, pe: 40, marketCap: 250 },
  { ticker: 'BAC', title: 'Bank of America Corp.', sector: 'Financials', profitMargin: 0.26, pe: 14, marketCap: 350 },
  { ticker: 'KO', title: 'Coca-Cola Co.', sector: 'Consumer Staples', profitMargin: 0.22, pe: 28, marketCap: 250 },
  { ticker: 'PFE', title: 'Pfizer Inc.', sector: 'Healthcare', profitMargin: 0.23, pe: 20, marketCap: 300 },
  { ticker: 'INTC', title: 'Intel Corp.', sector: 'Technology', profitMargin: 0.18, pe: 15, marketCap: 200 },
  { ticker: 'CSCO', title: 'Cisco Systems Inc.', sector: 'Technology', profitMargin: 0.24, pe: 18, marketCap: 220 },
  { ticker: 'WMT', title: 'Walmart Inc.', sector: 'Consumer Staples', profitMargin: 0.04, pe: 22, marketCap: 400 },
  { ticker: 'ORCL', title: 'Oracle Corp.', sector: 'Technology', profitMargin: 0.30, pe: 19, marketCap: 250 },
  { ticker: 'BA', title: 'Boeing Co.', sector: 'Industrials', profitMargin: 0.05, pe: 20, marketCap: 150 },
];

export const dummyData = [
  {
    date: 'Mar 22',
    Apples: 2890,
    Oranges: 2338,
    Tomatoes: 2452,
  },
  {
    date: 'Mar 23',
    Apples: 2756,
    Oranges: 2103,
    Tomatoes: 2402,
  },
  {
    date: 'Mar 24',
    Apples: 3322,
    Oranges: 986,
    Tomatoes: 1821,
  },
  {
    date: 'Mar 25',
    Apples: 3470,
    Oranges: 2108,
    Tomatoes: 2809,
  },
  {
    date: 'Mar 26',
    Apples: 3129,
    Oranges: 1726,
    Tomatoes: 2290,
  },
];
